var table_info_extractor_8py =
[
    [ "rapportsystem-backend.Requests.dataHandler.tableInfoExtractor.table_info_extractor", "classrapportsystem-backend_1_1_requests_1_1data_handler_1_1table_info_extractor_1_1table__info__extractor.html", "classrapportsystem-backend_1_1_requests_1_1data_handler_1_1table_info_extractor_1_1table__info__extractor" ]
];