# Description: This file contains the API key for the application. This key is used to authenticate the user and allow them to access the application.
# The API key will be autogenerated later.
def getAPIKey():
    API_KEY = 'TESTKEY' 
    return API_KEY